include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Empfohlene Regeln für sauberen Code
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_single_quotes: true
    require_trailing_commas: true
